In [9]:
import pandas as pd
import joblib
import os

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

In [2]:
train_path = "../../Dataset/processed/train_data.csv"
test_path = "../../Dataset/processed/test_data.csv"

train_data = pd.read_csv(train_path)
test_data = pd.read_csv(test_path)

print("Training data loaded successfully")
print("Testing data loaded successfully")

print("Training shape:", train_data.shape)
print("Testing shape:", test_data.shape)

Training data loaded successfully
Testing data loaded successfully
Training shape: (1356, 2461)
Testing shape: (340, 2461)

In [3]:
X_train = train_data.drop(columns=["Revenue(INR)"])
y_train = train_data["Revenue(INR)"]

X_test = test_data.drop(columns=["Revenue(INR)"])
y_test = test_data["Revenue(INR)"]

print("Number of input features:", X_train.shape[1])
print("Target column:", "Revenue(INR)")

Number of input features: 2460
Target column: Revenue(INR)

In [4]:
model_path = "../models/elastic_net_model.pkl"

if os.path.exists(model_path):
    print("Model file found")
    print("Model path: ", model_path)
else:
    print("Model file not found")

Model file found
Model path:  ../models/elastic_net_model.pkl

In [5]:
model = joblib.load(model_path)

print("Elastic Net model loaded successfully")
print(model)

Elastic Net model loaded successfully
Pipeline(steps=[('scaler', StandardScaler()),
                ('elastic_net',
                 ElasticNet(alpha=0.1, max_iter=10000, random_state=42))])

In [6]:
y_pred = model.predict(X_test)

print("Predictions successful")
print("Number of predictions: ", len(y_pred))

Predictions successful
Number of predictions:  340

In [8]:
prediction_data = pd.DataFrame({
    "Actual Revenue": y_test.values,
    "Predicted Revenue": y_pred
})

prediction_data.head(10)

   Actual Revenue  Predicted Revenue
0     230000000.0       3.125818e+08
1     350000000.0       3.413746e+08
2      80000000.0      -3.377649e+07
3     160000000.0       1.000698e+08
4      20000000.0       5.067319e+07
5      70000000.0      -2.303645e+07
6       3000000.0       7.167496e+06
7      20000000.0       4.741470e+07
8     190000000.0       4.400744e+08
9      80000000.0       4.895662e+07

In [10]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", round(mae, 2))
print("MSE :", round(mse, 2))
print("RMSE:", round(rmse, 2))
print("R²  :", round(r2, 4))

MAE : 66956283.08
MSE : 1.2780370698296384e+16
RMSE: 113050301.63
R²  : 0.7937

In [11]:
model_info = {
    "model_name": "Elastic Net Regression",
    "target": "Revenue(INR)",
    "number_of_features": X_train.shape[1],
    "training_samples": X_train.shape[0],
    "testing_samples": X_test.shape[0],
    "alpha": model.named_steps["elastic_net"].alpha,
    "l1_ratio": model.named_steps["elastic_net"].l1_ratio,
    "mae": mae,
    "mse": mse,
    "rmse": rmse,
    "r2": r2
}

for key, value in model_info.items():
    print(key, ":", value)

model_name : Elastic Net Regression
target : Revenue(INR)
number_of_features : 2460
training_samples : 1356
testing_samples : 340
alpha : 0.1
l1_ratio : 0.5
mae : 66956283.08245439
mse : 1.2780370698296384e+16
rmse : 113050301.62850687
r2 : 0.7936998811005649

In [12]:
model_info_df = pd.DataFrame(
    [model_info]
)

model_info_df.to_csv(
    "../../Dataset/processed/model_information.csv",
    index=False
)

print("Model information saved successfully")

Model information saved successfully

In [13]:
final_model_path = "../models/final_elastic_net_model.pkl"

joblib.dump(
    model,
    final_model_path
)

print("Final model saved successfully")
print("Path:", final_model_path)

Final model saved successfully
Path: ../models/final_elastic_net_model.pkl

In [14]:
final_model = joblib.load(final_model_path)

print("Final model loaded successfully")

Final model loaded successfully

In [15]:
final_predictions = final_model.predict(X_test)

print("Final model prediction successful")
print("First 5 predictions:")
print(final_predictions[:5])

Final model prediction successful
First 5 predictions:
[ 3.12581838e+08  3.41374593e+08 -3.37764901e+07  1.00069794e+08
  5.06731855e+07]

In [16]:
prediction_check = pd.DataFrame({
    "Original Prediction": y_pred[:5],
    "Final Model Prediction": final_predictions[:5]
})

prediction_check

   Original Prediction  Final Model Prediction
0         3.125818e+08            3.125818e+08
1         3.413746e+08            3.413746e+08
2        -3.377649e+07           -3.377649e+07
3         1.000698e+08            1.000698e+08
4         5.067319e+07            5.067319e+07

In [17]:
print("==========================================")
print("       FINAL MODEL INFORMATION")
print("==========================================")

print("Model:", model_info["model_name"])
print("Target:", model_info["target"])
print("Features:", model_info["number_of_features"])
print("Training samples:", model_info["training_samples"])
print("Testing samples:", model_info["testing_samples"])

print("\nModel Parameters")
print("Alpha:", model_info["alpha"])
print("L1 Ratio:", model_info["l1_ratio"])

print("\nEvaluation")
print("MAE:", round(model_info["mae"], 2))
print("MSE:", round(model_info["mse"], 2))
print("RMSE:", round(model_info["rmse"], 2))
print("R²:", round(model_info["r2"], 4))

print("\nFinal model:")
print(final_model_path)

==========================================
       FINAL MODEL INFORMATION
==========================================
Model: Elastic Net Regression
Target: Revenue(INR)
Features: 2460
Training samples: 1356
Testing samples: 340

Model Parameters
Alpha: 0.1
L1 Ratio: 0.5

Evaluation
MAE: 66956283.08
MSE: 1.2780370698296384e+16
RMSE: 113050301.63
R²: 0.7937

Final model:
../models/final_elastic_net_model.pkl